services:
  - type: web
    name: libretranslate
    env: python
    buildCommand: |
      pip install -r libretranslate/requirements.txt
      chmod +x build.sh
      ./build.sh
    startCommand: gunicorn 'wsgi:app' --bind 0.0.0.0:$PORT --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: LT_HOST
        value: 0.0.0.0
      - key: LT_UPDATE_MODELS
        value: false
      - key: LT_LOAD_ONLY
        value: en,es,fr,de,it,pt,ru,zh,ja,ko
      - key: PROMETHEUS_MULTIPROC_DIR
        value: /tmp/prometheus_data
